### ISSUE TITLE
Can i haz the GDV-Glossar as anki plz?

### ISSUE THREAD

**Issue by sthinbetween** [importPI19fromDHGE/dhge-pi19-sem5#114]
@RvNovae Wo wird denn das Anki-Deck fürs Glossar nach Erstellung hingepackt? Ich suche mir hier gerade nen Wolf :D

**Comment by RvNovae** [comment]
Das wird aktuell leider nicht automatisch gebaut :(

Ich hab mir selbst eins mit md2apkg gebastelt:
https://cloud.rvnovae.com/s/NcXEpTtapLXz2oo

**Comment by sthinbetween** [comment]
versuchen wir es in #115

**Comment by sthinbetween** [comment]
closed with #115

**Comment by sthinbetween** [comment]
wird erstellt, taucht aber in den Releases noch nicht auf.

**Comment by photovoltex** [comment]
habs auch bereits gemerkt und auch den Fehler gefunden denk ich
![image](https://user-images.githubusercontent.com/36958734/143269906-7a904ea8-d101-4e82-ab7b-533b7331781f.png)

Anscheinend muss der Name in only Großbuchstaben geschrieben sein aka `Glossar` ist ungültig und wird nicht released :D

**Comment by sthinbetween** [comment]
haha, bin gerade auch an der Stelle gelandet. Habe mich gewundert, warum das File in Atifact-output ist, aber nicht released wird.

**Comment by sthinbetween** [comment]
jetzt in #116

**Comment by sthinbetween** [comment]
Jetzt läufts
