### ISSUE TITLE
Klausurdokumentation

### ISSUE THREAD

**Issue by nukerxy** [importPI19fromDHGE/dhge-pi19-sem5#122]
Für jedes Fach soll grob nachgehalten werden, 

- welche Arten der Aufgabenstellung
- welche Schwerpunkte
- welche Schwierigkeit 

sich ergeben haben

**Comment by sthinbetween** [comment]
Würde ein extra Dokument jeweils im appendix vorschlagen?

**Comment by nukerxy** [comment]
jo, gute Idee
appendix/Klausur.md - bei GDV vor die Liste dazu
