### ISSUE TITLE
NET-Barie PDF ist leer

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem5#26]

**Comment by nukerxy** [comment]
oh no

**Comment by nukerxy** [comment]
Ich glaube da wurde zu schnell gemerged, der WF geskippt.
Create PDF release from markdown #131 läuft nach manuellem Start

**Comment by ZeroPointMax** [comment]
[Link](https://github.com/importPI19fromDHGE/dhge-pi19-sem5/actions/runs/1250938248)

**Comment by ZeroPointMax** [comment]
Also da @Steve2955 die Action sehr verbessert hat, haben wir auch ein anderes Verhalten zu früher: silent fails bei Generierungsfehlern.

![image](https://user-images.githubusercontent.com/26359277/133939799-f7f8fd55-647c-4185-a81b-d679f2dad4b0.png)
