### ISSUE TITLE
Anki NET-Barie

### ISSUE THREAD

**Issue by nukerxy** [importPI19fromDHGE/dhge-pi19-sem5#57]
see https://github.com/Steve2955/md2apkg/issues/33

**Comment by sthinbetween** [comment]
Kann es evt. etwas mit den Sonderzeichen in der Beschreibung zu tun haben? Nicht geschaut, nur geraten.

**Comment by RvNovae** [comment]
Wie in https://github.com/Steve2955/md2apkg/issues/32 ja bereits aufgefallen ist, wird dieser komplette Block am Anfang in den Titel geladen. Ich glaube also, dass die Sachen miteinander zusammen hängen. Vielleicht könnte man mal testen, ob Barie sich wandeln lässt, wenn man beim Anki-Konvertieren manuell einen Decknamen angibt (`-n`).

Hätte also zunächst auch die gleiche Vermutung, wie @sthinbetween

**Comment by ZeroPointMax** [comment]
Workaround in #107
