### ISSUE TITLE
ABWL - LKF - Organisation

### ISSUE THREAD

**Issue by nukerxy** [importPI19fromDHGE/dhge-pi19-sem5#64]
Wir möchten alle LKF in einer separaten Datei in diesem Repo "Anki-formatiert" sammeln.
/ABWL-Leder/appendix/LKF.md (Link folgt)

Für anderweitige Prüfungsvorbereitung **könnte** noch sowas wie [hier](https://github.com/Steve2955/dhge-pi19-sem5/blob/abwl-lkf/ABWL-LEDER/appendix/ZSM.md) entstehen.
Quasi eine Best-Of Datei, mit den wichtigsten Inhalten beider Vorlesungen.

Dieses Issue zur Dokumentation. Schließen, wenn das Semester vorbei ist.

**Comment by nukerxy** [comment]
Oliver hat noch einen verhungerten PR, den kann man sicherlich auch bei Erstellung der LKF mit einbeziehen.
https://github.com/importPI19fromDHGE/dhge-pi19-sem4/pull/123

**Comment by ZeroPointMax** [comment]
> Oliver hat noch einen verhungerten PR, den kann man sicherlich auch bei Erstellung der LKF mit einbeziehen. [importPI19fromDHGE/dhge-pi19-sem4#123](https://github.com/importPI19fromDHGE/dhge-pi19-sem4/pull/123)

kann die Branch mittlerweile weg @RvNovae ?

**Comment by RvNovae** [comment]
> kann die Branch mittlerweile weg @RvNovae ?

ist entfernt!

**Comment by ZeroPointMax** [comment]
Da die Sammelbranch gemergt ist, mach ich das mal zu
